// Vercel build step: write config.js from environment variables.
// Set SUPABASE_URL and SUPABASE_ANON_KEY in the Vercel project settings.
// If the env vars are missing, an existing committed/local config.js is kept.
const fs = require("fs");

const url = process.env.SUPABASE_URL || "";
const key = process.env.SUPABASE_ANON_KEY || "";

if (!url || !key) {
  if (fs.existsSync("config.js")) {
    console.warn("build.js: SUPABASE_URL/ANON_KEY not set — keeping existing config.js");
    process.exit(0);
  }
  console.error("build.js: SUPABASE_URL / SUPABASE_ANON_KEY env vars are required");
  process.exit(1);
}

const body =
  "// Generated by build.js from environment variables. Do not edit.\n" +
  "window.WAVE_CONFIG = " +
  JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: key }, null, 2) +
  ";\n";

fs.writeFileSync("config.js", body);
console.log("build.js: wrote config.js");
